### ISSUE TITLE
Kotlin Solutions

### ISSUE THREAD

**Issue by PedramVeisi** [careercup/CtCI-6th-Edition#133]
Hi,

I have started implementing the solutions in Kotlin. Would that be interesting?

The repo is here: https://github.com/PedramVeisi/CtCI-6th-Edition-Kotlin

Thanks.

**Comment by asaph** [comment]
@PedramVeisi We would love to include your Kotlin solutions. Please navigate to your repo's settings page and select the "Transfer Ownership" option, and specify @asaph (me) as the new owner. I'll then transfer it to the @careercup GitHub organization and add it as a submodule in the main repo. Thank you for your contribution!
--

**Comment by PedramVeisi** [comment]
@asaph Great! Done.

**Comment by asaph** [comment]
@PedramVeisi I've successfully transferred the Kotlin repo and added it to the main repo as a git submodule in commit ee6781560cb61c12a2b8cc3ef3493de3891d82c2. You should be able to still push to the Kotlin repo. You'll probably want to update your remote to reference https://github.com/careercup/CtCI-6th-Edition-Kotlin.git. Thanks again for your contribution!
