### ISSUE TITLE
Ch 01. Arrays and Strings Q1_06_String_Compression

### ISSUE THREAD

**Issue by shailendra-singh-dev** [careercup/CtCI-6th-Edition#158]
The solution which is given does not work for "aaaabbaa".

public static String compressBad(String str) {
		String compressedString = "";
		int countConsecutive = 0;
		for (int i = 0; i < str.length(); i++) {
			countConsecutive++;			
			/* If next character is different than current, append this char to result.*/
			if (i + 1 >= str.length() || str.charAt(i) != str.charAt(i + 1)) {
				compressedString += "" + str.charAt(i) + countConsecutive;
				countConsecutive = 0;
			}
		}
		return compressedString.length() < str.length() ? compressedString : str;
	}

I have provided below solution .

private static final HashMap<Character, Integer> map = new HashMap<Character, Integer>();
       public static String getCompressString(String str) {
		StringBuilder stringBuilder = new StringBuilder();
		HashMap<Character, Integer> map = getMap(str.toCharArray());
		for (Map.Entry<Character, Integer> entry : map.entrySet()) {
			stringBuilder.append(entry.getKey());
			stringBuilder.append(entry.getValue());
		}
                String finalStr = stringBuilder.toString();
		if (finalStr.length() <= str.length()) {
			return finalStr;
		}
		return str;
	}

	private static HashMap<Character, Integer> getMap(char[] a) {
		if (null == a || a.length == 0) {
			return null;
		}
               for (int i = 0; i < a.length; i++) {
			char ch = a[i];
			if (map.containsKey(ch)) {
				int count = map.get(ch);
				map.put(ch, ++count);
			} else {
				map.put(ch, 1);
			}
		}
	      return map;
	}

which works for any input "aabb" , "aaabbaaa" etc.
Any suggestion please provide.

**Comment by gaylemcd** [comment]
The original solution works for the proposed input, but your solution does not. The expected output for aaabbaaa is a3b2a3 (which is what the book's solution returns), not a6b2. The example provided in the book is aabcccccaaa -> a2b1c5a3. If you merely counted the number of characters (regardless of order), then there would be no way to distinguish between aaab and abaa (and therefore no way to decompress a3b1).

**Comment by shailendra-singh-dev** [comment]
Hi,
    Thanks, I got the problem statement now.

Thanks & Regards,
Shailendra Singh
Phone: +91-9886728081
Skype: shailendra-java
WhatsApp: ++91-9886728081
