### ISSUE TITLE
C# solution for 6th Edition

### ISSUE THREAD

**Issue by dww84** [careercup/CtCI-6th-Edition#84]
Requesting that my solution repo be promoted to join the careercup GitHub organization and referenced from the main repo as a git submodule.

Currently only partially completed an upgrade from Edition 5 and porting Edition 6 questions from Java solution. Work in progress, but better than nothing.

https://github.com/dww84/CtCI-6th-Edition-CSharp

**Comment by asaph** [comment]
Thank you for your contribution. Please go to the settings tab for your repo and click the transfer ownership button. Please designate me (@asaph) as the new repo owner and I'll move it into the @CareerCup organization and add it as a submodule in the main repo.

**Comment by asaph** [comment]
@dww84 Ok, all done. You should be able to still push to this repo. You'll probably want to update your remote to reference https://github.com/careercup/CtCI-6th-Edition-CSharp.git. Thanks again for your contribution!
