### ISSUE TITLE
New Repo for CtCI-6th-Edition-C

### ISSUE THREAD

**Issue by bhushan017** [careercup/CtCI-6th-Edition#86]
Request to create new repo for C solutions

**Comment by asaph** [comment]
Thank you for your contribution. Please go to the settings tab for your repo and click the transfer ownership button. Please designate me (@asaph) as the new repo owner and I'll transfer it into the @CareerCup organization and add it as a submodule in the main repo.

**Comment by asaph** [comment]
@bhushan017 I have transferred your c solutions repo to the @CareerCup organization. You should still be able to push to it and continue contributing directly. Although https://github.com/bhushan017/CtCI-6th-Edition-C redirects to the new location, it's still a good idea to update your remote to reference https://github.com/careercup/CtCI-6th-Edition-C.git. Thanks again for your contribution!
