### ISSUE TITLE
Request to add Ruby solutions

### ISSUE THREAD

**Issue by jasonsutter87** [careercup/CtCI-6th-Edition#97]
Hello!

I would like to offer Ruby solutions, and would like to be a contributor. 

Please check out my repo below.
https://github.com/jasonsutter87/CtCI-6th-Edition-Ruby

Thanks!
- Jason

**Comment by asaph** [comment]
@jasonsutter87 Please navigate to your repo's settings page and select the "Transfer Ownership" option, and specify @asaph (me) as the new owner. I'll then transfer it to the @CareerCup GitHub organization and add it as a submodule in the main repo. Thank you for your contribution!

**Comment by jasonsutter87** [comment]
- Repository transfer to Asaph requested

Thank you for accepting my contribution

**Comment by asaph** [comment]
@jasonsutter87 Your ruby solutions have been added. Thank you for your contribution!
